name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t ravi2977/lab-ui .
      - name: Publish image to Docker Hub
        run: docker push ravi2977/lab-ui:latest   

  deploy: 
    needs: build
    runs-on: self-hosted    
    steps:
      - name: Login to Docker Hub (Deploy)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Pull image from Docker Hub
        run: docker pull ravi2977/lab-ui:latest 
      - name: Delete Old Container
        run: docker rm -f reactContainer || true
      - name: Run Docker Container
        run: docker run -d -p 80:3000 --name reactContainer ravi2977/lab-ui
